%YAML 1.2
---
api:
  name: "accounts-sfdc-sapi"
  host: "0.0.0.0"
  port:  "8081"
  basepath: "/api/*"
  apiId: "19126396"
  layer: "System"
  
salesforce:
  url: "https://login.salesforce.com/services/Soap/u/56.0"
  connectiontiontimeout: "30"
  responsetimeout: "30000"
  reconnectionretry: "3"
  reconnectionfrequency: "2000"
  
error:
  errorDescription: Error occurred, please refer application logs for more details
  
errorMessage:
  BAD_REQUEST: BAD_REQUEST
  NOT_FOUND: NOT_FOUND
  METHOD_NOT_ALLOWED: METHOD_NOT_ALLOWED
  NOT_ACCEPTABLE: NOT_ACCEPTABLE
  UNSUPPORTED_MEDIA: UNSUPPORTED_MEDIA
  NOT_IMPLEMENTED: NOT_IMPLEMENTED
  CUSTOM_SERVICE_ERROR: CUSTOM_SERVICE_ERROR
  ANY: INTERNAL_SERVER_ERROR

errorCode:
  BAD_REQUEST: "400"
  NOT_FOUND: "404"
  METHOD_NOT_ALLOWED: "405"
  NOT_ACCEPTABLE: "406"
  UNSUPPORTED_MEDIA: "415"
  NOT_IMPLEMENTED: "501"
  CUSTOM_SERVICE_ERROR: "400"
  ANY: "500"  
 